# Generated by Django 5.1.7 on 2025-03-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slice_type', models.CharField(max_length=10)),
                ('timestamp', models.FloatField()),
                ('bytes_transmitted', models.IntegerField()),
            ],
        ),
    ]
