# Generated by Django 5.1.7 on 2025-03-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slice_simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='jitter',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='latency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='packet_loss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='signal_strength',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='throughput',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='bytes_transmitted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='slice_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='timestamp',
            field=models.FloatField(default=0),
        ),
    ]
